config/routes.rb
Rails.application.routes.draw do
  
 

  get "signup" => "users#new", as: :signup # give it a name
  get "login" => "sessions#new", as: :login
  delete "logout" => "sessions#destroy", as: :logout

  resources :listings
  resources :bids, only: [:index]
  
  resources :listings, only:[] do
    patch :publish, on: :member  
    resources :bids, on: :member
  end

  resources :sessions
  resources :users
  root "welcome#index"

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing

  validates :prices,        presence: {message: "must have prices"}, bid_price_min: true

  delegate :full_name,      to: :user,      prefix: true
  delegate :title,          to: :listing,   prefix: true
  delegate :detail,         to: :listing,  prefix: true
  delegate :reserve_price,  to: :listing,  prefix: true
  delegate :end_on,         to: :listing,  prefix: true

  after_create :change_reserve_price

  default_scope{order("created_at DESC")}

  
  attr_accessor :card_number, 
                :cvc,
                :card_month,
                :card_year,
                :stripe_card_token

  def change_reserve_price
    listing = self.listing
    listing.reserve_price = prices.to_i + 1
    listing.save
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_many :bids
  belongs_to :user

  validates :title,         presence: {message: "must have title"},         uniqueness: true
  validates :detail,        presence: {message: "must have detail"}
  validates :end_on,        presence: {message: "must have end_on"}
  validates :reserve_price, presence: {message: "must have reserve_price"}

  state_machine :state, initial: :draft do
    event :publish do
      transition draft: :published
    end

    event :complete do
      transition published: :target_met
    end

    event :expire do
      transition target_met: :succeeded, published: :failed
    end

    event :cancel do
      # transition [:draft, :published, :target_met] => :canceled
      transition any => :canceled
    end

    after_transition on: :canceled, do: :refund_all_bids
  end

  def sanitize
    self.detail.squeeze!(" ")
    self.detail.strip!
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password 
  has_many :listings
  has_many :bids

  # validates :email, presence: true, uniqueness: true, email_format: true

  def full_name
    if first_name || last_name
      "#{first_name} #{last_name}".squeeze(" ").strip
    else
      email
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user #linked to all views

  def authenticate_user!
    redirect_to login_path, alert: "You need to sign in" if current_user.nil?
  end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_listing , only: [:create, :destroy]
  before_action :not_current_user_listing?, only: [:create]

  def index
    @bids = current_user.bids
  end

  def create
    # token = params[:bid] ? params[:bid][:stripe_card_token] : ""
    # service = Bid::CreateBid.new(user: current_user,
    #                              stripe_token: token,
    #                              listing: @listing)

    # if service.call
    #   redirect_to @listing, notice: "Thank you"
    # else
    #   @bid = service.bid
    #   render :new
    # end
    @bid             = @listing.bids.new(bid_attributes)
    @bid.user        = current_user


    respond_to do |format| 
      if check_bid_price && @bid.save
        format.html {redirect_to @listing, notice: "Bid created successfully" }
        format.js { render }
      else
        format.js { render :error}
        format.html {redirect_to @listing, notice: "You must bid higher than $#{@listing.reserve_price}" } 
      end
    end
  end

  def destroy
    @bid = @listing.bids.find params[:id] 
    
    respond_to do |format|
      if @bid.user == current_user && @bid.destroy 
        format.html{redirect_to @listing, notice: "Bid deleted"}
        format.js { render }
      else
        format.html{redirect_to @listing, error: "We had trouble deleting"}
        format.js { render js: "alert('error');" }
      end
    end
  end

  private

  def bid_attributes
    params.require(:bid).permit([:prices])
  end

  def find_listing
    @listing = Listing.find(params[:listing_id])
  end

  def not_current_user_listing?
    redirect_to :back, notice: "you can't bid on your own auction item" unless @listing.user != current_user
  end

  def check_bid_price
    @bid.prices.to_i > @listing.reserve_price.to_i
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_listing, only: [:edit, :update, :destroy]

  def index
    @listings = current_user.listings.all
  end

  def show
     @listing = Listing.find(params[:id])
     @bid = Bid.new
  end

  def new
    @listing = Listing.new
  end

  def edit
  end

  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listings_path, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    @listing = current_user.listings.find params[:id]
    if @listing.publish
      redirect_to listings_path, notice: "Listing Published"
    else
      redirect_to listings_path, alert: "Listing Published Failed: #{@listing.errors.full_messages}"
    end
  end

  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_listing
      @listing = current_user.listings.find params[:id]
    end

    def listing_params
      params.require(:listing).permit(:title, :detail, :end_on, :reserve_price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    respond_to do |format|
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        format.html{ redirect_to root_path, notice: "Thanks for loggin in"}
        format.js do
          flash.now.notice = "Thanks for signing in"
          render
        end
      else
        flash.now[:alert] = "Email or password is invalid"
        format.html{render :new}
        format.js {render :new}
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You've been logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "thank you for registering"
    else
      flash.now[:alert] = "You need to fill all the fields"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit([:email, 
                                  :password, 
                                  :password_confirmation,
                                  :first_name,
                                  :last_name
                                  ])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @listings = Listing.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bids/_bid.html.haml
%p{id: dom_id(bid)}
  %span=bid.prices
  %span=bid.user_full_name
%hr/ 

app/views/bids/create.js.haml
$("#bid_listing").prepend("#{j render 'bid', bid: @bid}");
$("##{dom_id(@bid)}").hide().fadeIn(500);
$("#bid_prices").val("");

app/views/bids/error.js.haml
$("#notice").html("You must bid higher than $#{@listing.reserve_price}");

app/views/bids/index.html.haml
%table
  %thead
    %tr
      %th Title
      %th End on
      %th Reserve price
      %th Your bid price
  %tbody
    -@bids.each do |bid|
      %tr
        %td= bid.listing_title
        %td= bid.listing_end_on
        %td= bid.listing_reserve_price
        %td= bid.prices
        %td= link_to 'Show', bid.listing

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Auction
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application','https://js.stripe.com/v1/', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = tag :meta, name: "stripe-key", content: ENV["STRIPE_PUBLISHABLE_KEY"]
  %body
    -if current_user
      = current_user.full_name
      = link_to "Log Out", logout_path, method: :delete
      |
      = link_to "My Listings", listings_path
      |
      = link_to "My Biddings", bids_path

    -else
      = link_to "Sign In", login_path
      |
      = link_to "Sign Up", signup_path

    = yield

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="field">
    <%= f.label :end_on %><br>
    <%= f.datetime_select :end_on %>
  </div>
  <div class="field">
    <%= f.label :reserve_price %><br>
    <%= f.number_field :reserve_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Detail</th>
      <th>End on</th>
      <th>Reserve price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<%= link_to 'New Listing', new_listing_path %>
  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.detail.truncate(50) %></td>
        <td><%= listing.end_on %></td>
        <td><%= listing.reserve_price %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
          <% if listing.draft? %>
            <%=button_to "Publish", publish_listing_path(listing), method: :patch%>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.haml
%p
  %h1#notice= notice
%p
  %strong Title:
  = @listing.title
%p
  %strong Detail:
  = @listing.detail
%p
  %strong End on:
  = @listing.end_on
%p
  %strong Reserve price:
  = @listing.reserve_price

#stripe-error
-if @bid.errors[:base].present?
  =@bid.errors[:base].join(", ")
%p
  =simple_form_for [@listing, @bid], remote: true do |f|
    =f.input :prices
    / =f.input :stripe_card_token, as: :hidden
    / =f.input :card_number
    / =f.input :cvc
    / =f.input :card_month, as: :date, order: [:month]
    / =f.input :card_year, as: :date, order: [:year], start_year: Date.today.year, end_year: Date.today.year + 5
    =f.submit "submit", class: "btn btn-primary"

#bid_listing
  -@listing.bids.each do |bid|
    %p
      %span=bid.prices
      %span=bid.user_full_name
    %hr/ 

- if @listing.user == current_user
  = link_to 'Edit', edit_listing_path(@listing)
  |
= link_to 'Back', listings_path

app/views/users/new.html.haml
%h2 Sign Up For A New Account

= simple_form_for @user, html: {class: "form-horizontal"} do |f|
 = f.input :first_name
 = f.input :last_name
 = f.input :email
 = f.input :password
 = f.input :password_confirmation  
 = f.submit "Sign Up", class: "btn btn-primary"

app/views/welcome/index.html.erb
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Detail</th>
      <th>End on</th>
      <th>Reserve price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<%= link_to 'New Listing', new_listing_path %>
  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.detail.truncate(50) %></td>
        <td><%= listing.end_on %></td>
        <td><%= listing.reserve_price %></td>
        <td><%= link_to 'Show', listing %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>